#!/bin/bash

cd ..

COUNT=0
CURRENT_DIR="$PWD"
PD="build_tools/patches"
PATCHES=(
'hardware/libhardware           audio_fix.patch'
'bootable/recovery              bootable_recovery.patch'
'build              		build.patch'
'external/icu                   external_icu.patch'
'external/sepolicy              external_sepolicy.patch'
'external/tinyalsa              external_tinyalsa.patch'
'frameworks/av			frameworks_av.patch'
'frameworks/av			audio_fix2.patch'
'frameworks/base		frameworks_base.patch'
'frameworks/native		frameworks_native.patch'
'frameworks/opt/telephony	frameworks_opt_telephony.patch'
'hardware/broadcom/libbt	hardware_broadcom_libbt.patch'
'packages/apps/Settings         packages_apps_Settings.patch'
'packages/apps/Trebuchet        packages_apps_Trebuchet.patch'
'packages/services/Telephony	packages_services_Telephony.patch'
'system/core			system_core.patch'
'system/core                    microphone_fix.patch'
)

while [ "x${PATCHES[COUNT]}" != "x" ]
do
	CURRENT="${PATCHES[COUNT]}"
	FOLDER=`echo "$CURRENT" | awk '{print $1}'`
	PATCH=`echo "$CURRENT" | awk '{print $2}'`

	cd "$FOLDER"
	echo Patching "$FOLDER" ...
	git apply "$CURRENT_DIR/$PD/$PATCH"
	cd "$CURRENT_DIR"

	COUNT=$(($COUNT + 1))
done
